-- DROP COMMANDS TO DROP ALL THE TABLES CREATED
DROP TABLE RECOMMENDATIONS;
DROP TABLE REVIEWS;
DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;
DROP TABLE RESTAURANT_INVENTORY;
DROP TABLE MENU_ITEMS;
DROP TABLE WAITERS;
DROP TABLE RESTAURANTS;
DROP TABLE CUISINE;

-- DROP COMMANDS TO DROP ALL THE PROCEDURES CREATED
DROP PROCEDURE ADD_CUISINE;
DROP PROCEDURE ADD_NEW_RESTAURANT;
DROP PROCEDURE ADD_WAITER;
DROP PROCEDURE SHOW_WAITERS;
DROP PROCEDURE SHOW_TIPS_BY_WAITER;
DROP PROCEDURE SHOW_TIPS_BY_STATE;
DROP PROCEDURE ADD_MENU_ITEM;
DROP PROCEDURE ADD_ITEMS_INVENTORY;
DROP PROCEDURE ADD_CUSTOMERS;
DROP PROCEDURE ADD_ORDER;
DROP PROCEDURE ADD_REVIEW;
DROP PROCEDURE BUY_OR_BEWARE;
DROP PROCEDURE DISPLAY_RESTAURANTS_BY_CUISINE;
DROP PROCEDURE REPORT_INCOME;
DROP PROCEDURE GENERATE_REPORT_MENU_ITEMS;
DROP PROCEDURE UPDATE_MENU_ITEM_INVENTORY;
DROP PROCEDURE RECOMMEND_TO_CUSTOMER;
DROP PROCEDURE LIST_RECOMMENDATIONS;
DROP PROCEDURE LIST_ORDERS_AT_REST_ON_DATE;

-- DROP COMMANDS FOR ALL TRIGGERS CREATED
--DROP TRIGGER UPDATE_INVENTORY_AFTER_ORDER;

-- DROP COMMANDS TO DROP ALL THE FUNCTIONS CREATED
DROP FUNCTION FIND_CUISINE_TYPE_ID;
DROP FUNCTION FIND_RESTAURANT_ID;
DROP FUNCTION FIND_MENU_ITEM_ID;
DROP FUNCTION FIND_CUSTOMER_ID;
DROP FUNCTION FIND_WAITER_ID;


-- DROP COMMANDS TO DROP ALL THE SEQUENCE CREATED
DROP SEQUENCE CUISINE_ID_SEQUENCE;
DROP SEQUENCE RESTAURANT_ID_SEQUENCE;
DROP SEQUENCE WAITER_ID_SEQUENCE;
DROP SEQUENCE MENU_ITEM_SEQUENCE;
DROP SEQUENCE CUST_SEQUENCE;
DROP SEQUENCE ORD_SEQUENCE;
DROP SEQUENCE REST_INV_SEQUENCE;
DROP SEQUENCE REV_SEQUENCE;
DROP SEQUENCE RECOMMENDATION_ID_SEQUENCE;


-- CREATE SEQUENCE COMMAND FOR CUISINE ID
CREATE SEQUENCE CUISINE_ID_SEQUENCE
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE RESTAURANT_ID_SEQUENCE
START WITH 200
INCREMENT BY 1;

CREATE SEQUENCE WAITER_ID_SEQUENCE
START WITH 300
INCREMENT BY 1;


CREATE SEQUENCE MENU_ITEM_SEQUENCE
START WITH 400 
INCREMENT BY 1;

CREATE SEQUENCE REST_INV_SEQUENCE
START WITH 500
INCREMENT BY 1;

CREATE SEQUENCE CUST_SEQUENCE
START WITH 600
INCREMENT BY 1;

CREATE SEQUENCE ORD_SEQUENCE
START WITH 700
INCREMENT BY 1;

CREATE SEQUENCE REV_SEQUENCE
START WITH 800
INCREMENT BY 1;

CREATE SEQUENCE RECOMMENDATION_ID_SEQUENCE
START WITH 900
INCREMENT BY 1;


CREATE TABLE CUISINE(
    CUISINE_ID INT,
    CUISINE_NAME VARCHAR(50),
    PRIMARY KEY (CUISINE_ID)
);

/

CREATE TABLE RESTAURANTS(
    RESTAURANT_ID INT,
    RESTAURANT_NAME VARCHAR2(100),
    RESTAURANT_STREET_ADDRESS VARCHAR2(150),
    CITY VARCHAR2(100),
    RESTAURANT_STATE VARCHAR2(100),
    ZIP VARCHAR2(20),
    CUISINE_ID INT,
    PRIMARY KEY (RESTAURANT_ID),
    FOREIGN KEY (CUISINE_ID) REFERENCES CUISINE(CUISINE_ID)
);
/

-- CREATE TABLE COMMAND TO CREATE WAITERS TABLE
CREATE TABLE WAITERS (
    WAITER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR(100),
    RESTAURANT_ID NUMBER,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
);
/

-- CREATE TABLE COMMAND TO CREATE MENU ITEMS TABLE
CREATE TABLE MENU_ITEMS (
    MENU_ITEM_ID NUMBER PRIMARY KEY,
    CUISINE_ID NUMBER,
    NAME VARCHAR(100),
    PRICE NUMBER,
    CONSTRAINT FK_CUISINE_TYPES FOREIGN KEY (CUISINE_ID) REFERENCES CUISINE(CUISINE_ID)
);
/

-- CREATE TABLE COMMAND TO CREATE RESTAURANT INVENTORY TABLE
CREATE TABLE RESTAURANT_INVENTORY (
    INVENTORY_ID INT PRIMARY KEY,
    MENU_ITEM_ID NUMBER,
    MENU_ITEM_NAME VARCHAR(100),
    RESTAURANT_ID NUMBER,
    QUANTITY NUMBER, 
    CONSTRAINT FK_MENU_ITEM_INVENTORY FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID),
    CONSTRAINT FK_RESTAURANT_INVENTORY FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
);
/

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    STREET_ADDRESS VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    ZIPCODE VARCHAR(100),
    CREDIT_CARD_NUMBER VARCHAR(100)
);
/
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    RESTAURANT_ID INT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    MENU_ITEM_ID INT,
    WAITER_ID INT,
    AMOUNT_PAID FLOAT,
    TIP FLOAT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID),
    FOREIGN KEY (MENU_ITEM_ID) REFERENCES MENU_ITEMS(MENU_ITEM_ID),
    FOREIGN KEY (WAITER_ID) REFERENCES WAITERS(WAITER_ID)
);
/

-- CREATE TABLE COMMAND TO CREATE REVIEWS TABLE
CREATE TABLE REVIEWS (
    REVIEW_ID INT PRIMARY KEY,
    RESTAURANT_ID INT,
    REVIEW_TEXT VARCHAR(1000),
    STARS_GIVEN INT,
    REVIEWER_EMAIL VARCHAR(255),
    CONSTRAINT FK_REVIEW_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
);
/
-- CREATE RECOMMENDATIONS TABLE
CREATE TABLE RECOMMENDATIONS (
    RECOMMENDATION_ID NUMBER(38) PRIMARY KEY,
    CUSTOMER_ID NUMBER(38),
    RECOMMENDED_RESTAURANT_ID NUMBER(38),
    RECOMMENDATION_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
/


-- CREATE FUNCTION COMMAND TO FIND CUISINE TYPE ID
-- THIS FUNCTION IS USED TO RETRIEVE CUISINE TYPE ID WHEN CUISINE NAME IS PROVIDED
-- INPUT PARAMETER - CUISINE NAME
-- OUTPUT PARAMETER - CUISINE ID
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION FIND_CUISINE_TYPE_ID(CUISINE_NAME_VALUE IN VARCHAR2) RETURN INT IS
    CUISINE_ID_VALUE INT;
BEGIN
    SELECT CUISINE_ID INTO CUISINE_ID_VALUE FROM CUISINE WHERE CUISINE_NAME=CUISINE_NAME_VALUE;
    RETURN CUISINE_ID_VALUE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH CUISINE TYPE');
        RETURN -1;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN UNEXPECTED ERROR OCCURED');
        RETURN -1;
END;
/


-- CREATE FUNCTION COMMAND TO FIND RESTAURANT ID
SET SERVEROUTPUT ON;
CREATE OR REPLACE FUNCTION FIND_RESTAURANT_ID(R_NAME IN VARCHAR2) RETURN INT IS
    R_ID INT;
BEGIN
    SELECT RESTAURANT_ID INTO R_ID FROM RESTAURANTS WHERE RESTAURANT_NAME = R_NAME;
    RETURN R_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH RESTAURANT');
        RETURN -1;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN UNEXPECTED ERROR OCCURED');
        RETURN -1;
END;
/

CREATE OR REPLACE FUNCTION FIND_WAITER_ID(
    WAITER_NAME IN VARCHAR 
    )
RETURN NUMBER -- RETURN TYPE OF NUMBER FOR THIS FUNCTION
AS
    WAITER_ID NUMBER; 
BEGIN
    -- SELECT QUERY TO RETRIEVE WAITER ID WHEN WAITER NAME IS PROVIDED
    SELECT WAITER_ID INTO WAITER_ID
    FROM WAITERS
    WHERE NAME = WAITER_NAME;
    DBMS_OUTPUT.PUT_LINE('THE WAITER ID FOR ' || WAITER_NAME || ' IS ' || WAITER_ID);
    RETURN WAITER_ID;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA WAS FOUND');
        RETURN -1; 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN UNEXPECTED ERROR OCCURRED');
        RETURN -1; 
END;
/

CREATE OR REPLACE FUNCTION FIND_MENU_ITEM_ID (ITEM_NAME IN VARCHAR2) RETURN NUMBER
IS
    ITEM_ID NUMBER;
BEGIN
    SELECT MENU_ITEM_ID INTO ITEM_ID 
    FROM MENU_ITEMS 
    WHERE NAME = ITEM_NAME;     
    RETURN ITEM_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH MENU ITEM');
        RETURN -1;
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('AN UNEXPECTED ERROR OCCURRED');
        RETURN -1;
END;
/

CREATE OR REPLACE FUNCTION FIND_CUSTOMER_ID (CUSTOMER_NAME IN VARCHAR2) RETURN NUMBER
IS
    CUSTOMERID NUMBER;
BEGIN
    SELECT CUSTOMER_ID INTO CUSTOMERID 
    FROM CUSTOMERS 
    WHERE NAME = CUSTOMER_NAME;
    RETURN CUSTOMERID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO SUCH CUSTOMER');
        RETURN -1;
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('AN UNEXPECTED ERROR OCCURRED');
        RETURN -1;
END;
/


--CREATE PROCEDURE TO ADD CUISINE TYPE
--THIS PROCEDURE IS USED TO INSERT VALUES INTO TABLE
-- INPUT PARAMETER - CUISINE NAME 
-- OUTPUT - INSERTION OF VALUES INTO CUISINE TYPE TABLE
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE ADD_CUISINE(CUISINE_NAME_VALUE IN VARCHAR2)IS
BEGIN
    INSERT INTO CUISINE VALUES(CUISINE_ID_SEQUENCE.NEXTVAL,CUISINE_NAME_VALUE);
    DBMS_OUTPUT.PUT_LINE('CUISINE_NAME INSERTED ' || CUISINE_NAME_VALUE);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN ERROR OCCURRED: ' || SQLERRM);
END;
/

-- COMMAND TO CREATE PROCEDURE TO ADD NEW RESTAURANT INTO RESTAURANT TABLE
SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE ADD_NEW_RESTAURANT(
    R_NAME IN VARCHAR2,
    R_ADDRESS IN VARCHAR2,
    R_CITY IN VARCHAR2,
    R_STATE IN VARCHAR2,
    R_ZIP IN VARCHAR2,
    CUISINE_NAME_VALUE IN VARCHAR2
) IS
    CUISINE_ID_VALUE INT;
BEGIN
    --GET CUISINE ID
    CUISINE_ID_VALUE := FIND_CUISINE_TYPE_ID(CUISINE_NAME_VALUE);
    --INSERT NEW RESTAURANTS
    INSERT INTO RESTAURANTS VALUES(RESTAURANT_ID_SEQUENCE.NEXTVAL,R_NAME,R_ADDRESS,R_CITY,R_STATE,R_ZIP,CUISINE_ID_VALUE);
    DBMS_OUTPUT.PUT_LINE('INSERTED VALUES ARE: ' || R_NAME ||'  '|| R_ADDRESS ||'  '||  R_CITY ||'  '|| R_STATE ||'  '|| R_ZIP ||'  '|| CUISINE_ID_VALUE);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN ERROR OCCURRED: ' || SQLERRM);
END;
/

-- CREATE PROCEDURE TO ADD WAITER
-- THIS PROCEDURE IS USED TO INSERT VALUES INTO TABLE
-- OUTPUT - INSERTION OF VALUES INTO RESTAURENT TYPE TABLE
CREATE OR REPLACE PROCEDURE ADD_WAITER(
    WAITERNAMEVALUE IN VARCHAR, RESTAURANTNAMEVALUE IN VARCHAR) -- INPUT PARAMETER
    IS
    RESTIDVALUE NUMBER;
BEGIN
    -- INSERT QUERY WITH SEQUENCE FOR WAITERS_ID STARTING FROM 300
    RESTIDVALUE := FIND_RESTAURANT_ID(RESTAURANTNAMEVALUE);
   
    INSERT INTO WAITERS (WAITER_ID, NAME, RESTAURANT_ID) VALUES (WAITER_ID_SEQUENCE.NEXTVAL, WAITERNAMEVALUE, RESTIDVALUE);
        DBMS_OUTPUT.PUT_LINE(WAITERNAMEVALUE || ' ADDED SUCCESSFULLY');
    EXCEPTION WHEN OTHERS THEN
        -- EXCEPTION HANDLING
        DBMS_OUTPUT.PUT_LINE('ERROR ADDING WAITER: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE SHOW_WAITERS(REST_NAME IN VARCHAR, WAIT_NAME OUT VARCHAR) IS -- PROCEDURE TO SHOW THE WAITERS AT A PARTICULAR RESTAURANT
REST_ID INT := FIND_RESTAURANT_ID(REST_NAME); --CALLS THE FIND RESTAURANT ID FUNCTION; THE WAITER TABLE HAS THE RESTAURANT ID AS A FOREIGN KEY
CURSOR SHOW_WAITER IS SELECT WAITERS.NAME FROM WAITERS WHERE REST_ID = WAITERS.RESTAURANT_ID; --CREATES A CURSOR THAT GETS THE WAITERS WHO WORK AT THE SPECIFIED RESTAURANT
BEGIN
OPEN SHOW_WAITER; --OPEN THE CURSOR
LOOP
FETCH SHOW_WAITER INTO WAIT_NAME; --GET THE WAITER'S NAME FROM THE WAITER TABLE
EXIT WHEN SHOW_WAITER%NOTFOUND; -- EXIT
DBMS_OUTPUT.PUT_LINE(WAIT_NAME); --PRINT OUT THE WAITER'S NAME
END LOOP;
EXCEPTION
WHEN NO_DATA_FOUND THEN --HANDLE EXCEPTIONS
DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
END;
/

CREATE OR REPLACE PROCEDURE SHOW_TIPS_BY_WAITER (WAIT_NAME IN VARCHAR, WAIT_TIPS OUT NUMBER) IS --PROCEDURE TO SHOW TIPS BY WAITER
WAIT_ID INT := FIND_WAITER_ID(WAIT_NAME); -- CALLS THE FIND WAITER ID FUNCTION
IND_TIP NUMBER := 0;
TOTAL_TIPS NUMBER := 0;
CURSOR SHOW_TIPS_WAITER IS SELECT TIP FROM ORDERS WHERE WAIT_ID = ORDERS.WAITER_ID; -- CREATE A CURSOR TO GET THE INDIVIDUAL TYPE
BEGIN
OPEN SHOW_TIPS_WAITER; -- OPEN THE CURSOR
LOOP
FETCH SHOW_TIPS_WAITER INTO IND_TIP; 
EXIT WHEN SHOW_TIPS_WAITER%NOTFOUND; --EXIT
TOTAL_TIPS:= TOTAL_TIPS + IND_TIP;
END LOOP;
DBMS_OUTPUT.PUT_LINE(WAIT_NAME || 'S TIPS: $' || TOTAL_TIPS);
EXCEPTION -- HANDLE EXCEPTIONS
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
END;
/

CREATE OR REPLACE PROCEDURE SHOW_TIPS_BY_STATE (STATE_NAME IN VARCHAR2, STATE_TIPS OUT NUMBER) IS
    TOTAL_TIPS NUMBER := 0;
BEGIN
    SELECT NVL(SUM(O.TIP), 0) INTO TOTAL_TIPS
    FROM ORDERS O
    JOIN RESTAURANTS R ON O.RESTAURANT_ID = R.RESTAURANT_ID
    WHERE R.RESTAURANT_STATE = STATE_NAME;
    
    STATE_TIPS := TOTAL_TIPS;
    DBMS_OUTPUT.PUT_LINE('TIPS FOR ' || STATE_NAME || ': $' || TOTAL_TIPS);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
END;
/

CREATE OR REPLACE PROCEDURE ADD_MENU_ITEM(
   MENUNAME VARCHAR2,
   PRICE NUMBER,
   CUISINE_TYPE VARCHAR2
) AS
   CUISINE_ID NUMBER;
BEGIN
   CUISINE_ID := FIND_CUISINE_TYPE_ID(CUISINE_TYPE);
 
   INSERT INTO MENU_ITEMS (MENU_ITEM_ID, CUISINE_ID, NAME, PRICE)
   VALUES (MENU_ITEM_SEQUENCE.NEXTVAL, CUISINE_ID, MENUNAME, PRICE);
 
   -- COMMITTING THE TRANSACTION TO MAKE THE CHANGE PERMANENT
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE ('SQLCODE: ' || SQLCODE); -- OUTPUTS THE SQL ERROR CODE
       DBMS_OUTPUT.PUT_LINE ('SQLERRM: ' || SQLERRM); -- OUTPUTS THE ERROR MESSAGE
END ADD_MENU_ITEM;
/

 
-- CREATING PROCEDURE TO ADD INVENTORY
CREATE OR REPLACE PROCEDURE ADD_ITEMS_INVENTORY(
   MENU_NAME VARCHAR2,
   RESTAURANTNAMEVALUE VARCHAR2,
   QUANTITYVALUE NUMBER
) AS
   MENU_ITEMS_ID NUMBER;
   RESTAURANTS_ID NUMBER;
BEGIN
   RESTAURANTS_ID := FIND_RESTAURANT_ID (RESTAURANTNAMEVALUE);
   MENU_ITEMS_ID := FIND_MENU_ITEM_ID (MENU_NAME);
 
   INSERT INTO RESTAURANT_INVENTORY (INVENTORY_ID, MENU_ITEM_ID, MENU_ITEM_NAME, RESTAURANT_ID,QUANTITY)
   VALUES (REST_INV_SEQUENCE.NEXTVAL,MENU_ITEMS_ID, MENU_NAME,RESTAURANTS_ID , QUANTITYVALUE);
 
   -- COMMITTING THE TRANSACTION TO MAKE THE CHANGE PERMANENT
   COMMIT;
EXCEPTION
   WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE ('SQLCODE: ' || SQLCODE);
       DBMS_OUTPUT.PUT_LINE ('SQLERRM: ' || SQLERRM);
END ADD_ITEMS_INVENTORY;
/
-- CREATE PROCEDURE TO ADD CUSTOMERS
-- THIS PROCEDURE IS USED TO INSERT VALUES INTO TABLE
-- OUTPUT PARAMETER - INSERTION OF VALUES INTO INSERT CUSTOMERS TABLE
CREATE OR REPLACE PROCEDURE ADD_CUSTOMERS(
    CUST_NAME_VALUE VARCHAR,
    CUST_EMAIL_VALUE VARCHAR, 
    CUST_STREETADD_VALUE VARCHAR, 
    CUST_CITY_VALUE VARCHAR, 
    CUST_STATE_VALUE VARCHAR, 
    CUST_ZIP_VALUE VARCHAR, 
    CUST_CCNO_IN VARCHAR) --INPUT PARAMETERS 
AS
BEGIN
    -- INSERT QUERY WITH SEQUENCE FOR INSERT CUSTOMERS STARTING FROM 600
    INSERT INTO CUSTOMERS VALUES (
    CUST_SEQUENCE.NEXTVAL, 
    CUST_NAME_VALUE, 
    CUST_EMAIL_VALUE, 
    CUST_STREETADD_VALUE, 
    CUST_CITY_VALUE, 
    CUST_STATE_VALUE, 
    CUST_ZIP_VALUE, 
    CUST_CCNO_IN);
    
    DBMS_OUTPUT.PUT_LINE('CUSTOMER ' || CUST_NAME_VALUE || ' ADDED SUCCESSFULLY');
    
EXCEPTION --EXCEPTION HANDLING
    WHEN OTHERS THEN -- USED TO HANDLE EXCEPTION AND PRINT THE SQL ERROR MESSAGE
    DBMS_OUTPUT.PUT_LINE('ERROR FOUND ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE ADD_ORDER (
    REST_NAME VARCHAR,
    CUST_NAME VARCHAR, 
    MENU_NAME VARCHAR, 
    WAITER_NAME VARCHAR, 
    ORD_DATE DATE, 
    AMOUNT FLOAT) 
AS
    CUST_ID NUMBER;
    REST_ID NUMBER;
    MENU_ID NUMBER;
    WAITER_ID NUMBER;
    TIP FLOAT;
    AVAILABLE_QUANTITY NUMBER;
BEGIN
    -- Get IDs for restaurant, customer, menu item, and waiter
    REST_ID := FIND_RESTAURANT_ID(REST_NAME);
    CUST_ID := FIND_CUSTOMER_ID(CUST_NAME);
    MENU_ID := FIND_MENU_ITEM_ID(MENU_NAME);
    WAITER_ID := FIND_WAITER_ID(WAITER_NAME);
    TIP := AMOUNT * 0.2; 

    -- Check the available quantity in the inventory
    SELECT QUANTITY INTO AVAILABLE_QUANTITY
    FROM RESTAURANT_INVENTORY
    WHERE RESTAURANT_ID = REST_ID AND MENU_ITEM_ID = MENU_ID;

    IF AVAILABLE_QUANTITY > 0 THEN
        -- Insert the order if the item is available
        INSERT INTO ORDERS VALUES (ORD_SEQUENCE.NEXTVAL, REST_ID, CUST_ID, ORD_DATE, MENU_ID, WAITER_ID, AMOUNT, TIP);
        DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME ' || CUST_NAME || ' PLACED ORDER AT RESTAURANT ' || REST_NAME);
    ELSE
        DBMS_OUTPUT.PUT_LINE('ORDER NOT PLACED: ITEM NOT AVAILABLE');
    END IF;

EXCEPTION 
    WHEN DUP_VAL_ON_INDEX THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR ADDING ORDER: DUPLICATE ORDER');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('ERROR ADDING ORDER: ' || SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE ADD_REVIEW(
    P_REVIEWER_EMAIL IN VARCHAR2,
    P_RESTAURANT_NAME IN VARCHAR2,
    P_STARS_GIVEN IN NUMBER,
    P_REVIEW_TEXT IN VARCHAR2
)
IS
    V_REVIEW_ID NUMBER;
    V_RESTAURANT_ID NUMBER;
BEGIN
    -- FIND THE RESTAURANT ID USING THE HELPER FUNCTION
    V_RESTAURANT_ID := FIND_RESTAURANT_ID(P_RESTAURANT_NAME);
    
    IF V_RESTAURANT_ID IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: RESTAURANT NOT FOUND.');
        RETURN;
    END IF;
    
    -- INSERT QUERY WITH SEQUENCE FOR ADD REVIEW STARTING FROM 800
    -- INSERT QUERY TO ADD ITEMS INTO REVIEWS TABLE
    INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, REVIEW_TEXT, STARS_GIVEN, REVIEWER_EMAIL)
    VALUES (REV_SEQUENCE.NEXTVAL, V_RESTAURANT_ID, P_REVIEW_TEXT, P_STARS_GIVEN, P_REVIEWER_EMAIL);
    DBMS_OUTPUT.PUT_LINE('REVIEW ADDED SUCCESSFULLY BY ' || P_REVIEWER_EMAIL);
    
EXCEPTION --EXCEPTION HANDLING
    WHEN OTHERS THEN -- USED TO HANDLE EXCEPTION AND PROVIDE THE SQL ERROR MESSAGE
    DBMS_OUTPUT.PUT_LINE('ERROR ADDING REVIEW. ERROR CODE: ' || SQLERRM);
END;
/


-- CREATE BUY_OR_BEWARE PROCEDURE

create or replace PROCEDURE BUY_OR_BEWARE(P_X IN NUMBER)
IS
    -- Cursor for top rated restaurants
    CURSOR top_restaurants_cur IS
        SELECT ROUND(AVG(R.STARS_GIVEN), 1) AS AVG_STARS,
               R.RESTAURANT_ID,
               C.CUISINE_NAME,
               ROUND(STDDEV(R.STARS_GIVEN), 1) AS STD_DEV
        FROM REVIEWS R
        INNER JOIN RESTAURANTS RES ON R.RESTAURANT_ID = RES.RESTAURANT_ID
        INNER JOIN CUISINE C ON RES.CUISINE_ID = C.CUISINE_ID
        GROUP BY R.RESTAURANT_ID, C.CUISINE_NAME
        ORDER BY AVG_STARS DESC;

    -- Cursor for worst rated restaurants
    CURSOR worst_restaurants_cur IS
        SELECT ROUND(AVG(R.STARS_GIVEN), 1) AS AVG_STARS,
               RES.RESTAURANT_ID,
               RES.RESTAURANT_NAME,
               C.CUISINE_NAME,
               ROUND(STDDEV(R.STARS_GIVEN), 1) AS STD_DEV
        FROM REVIEWS R
        INNER JOIN RESTAURANTS RES ON R.RESTAURANT_ID = RES.RESTAURANT_ID
        INNER JOIN CUISINE C ON RES.CUISINE_ID = C.CUISINE_ID
        GROUP BY RES.RESTAURANT_ID, RES.RESTAURANT_NAME, C.CUISINE_NAME
        ORDER BY AVG_STARS ASC;

    v_counter NUMBER := 0; -- Counter to track the number of restaurants processed

BEGIN
    -- PRINT 'TOP RATED RESTAURANTS'
    -- PRINT 'TOP RATED RESTAURANTS'
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('TOP RATED RESTAURANTS');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');

    -- Loop through top rated restaurants
    FOR top_rest IN top_restaurants_cur LOOP
        v_counter := v_counter + 1;
        EXIT WHEN v_counter > P_X; -- Exit loop when desired number of restaurants is processed
        DBMS_OUTPUT.PUT_LINE('Average stars: ' || top_rest.AVG_STARS ||
                             ', Restaurant ID: ' || top_rest.RESTAURANT_ID ||
                             ', Cuisine: ' || top_rest.CUISINE_NAME ||
                             ', Standard deviation: ' || top_rest.STD_DEV);
    END LOOP;

    -- Reset counter for worst rated restaurants
    v_counter := 0;

    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
    -- PRINT 'BUYER BEWARE: STAY AWAY FROM...'
    DBMS_OUTPUT.PUT_LINE('BUYER BEWARE: STAY AWAY FROM...');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');

    -- Loop through worst rated restaurants
    FOR worst_rest IN worst_restaurants_cur LOOP
        v_counter := v_counter + 1;
        EXIT WHEN v_counter > P_X; -- Exit loop when desired number of restaurants is processed
        DBMS_OUTPUT.PUT_LINE('Average stars: ' || worst_rest.AVG_STARS ||
                             ', Restaurant ID: ' || worst_rest.RESTAURANT_ID ||
                             ', Restaurant name: ' || worst_rest.RESTAURANT_NAME ||
                             ', Cuisine: ' || worst_rest.CUISINE_NAME ||
                             ', Standard deviation: ' || worst_rest.STD_DEV);
    END LOOP;
END BUY_OR_BEWARE;
/

CREATE OR REPLACE PROCEDURE DISPLAY_RESTAURANTS_BY_CUISINE(
    CUISINE_NAME_VALUE IN VARCHAR2
)
AS
    CUISINE_ID_VALUE INT;
    CURSOR CUR_RESTAURANT IS
        SELECT RESTAURANT_NAME, RESTAURANT_STREET_ADDRESS
        FROM RESTAURANTS
        WHERE CUISINE_ID = CUISINE_ID_VALUE;

BEGIN
    CUISINE_ID_VALUE := FIND_CUISINE_TYPE_ID(CUISINE_NAME_VALUE);

    IF CUISINE_ID_VALUE IS NOT NULL THEN
        FOR RESTAURANT_INFO IN CUR_RESTAURANT LOOP
            DBMS_OUTPUT.PUT_LINE('RESTAURANT NAME: ' || RESTAURANT_INFO.RESTAURANT_NAME || ', ADDRESS: ' || RESTAURANT_INFO.RESTAURANT_STREET_ADDRESS);
        END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('CUISINE TYPE ' || CUISINE_NAME_VALUE || ' DOES NOT EXIST.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED WHILE DISPLAYING RESTAURANTS BY CUISINE.');
END;

/

CREATE OR REPLACE PROCEDURE REPORT_INCOME
IS
    CURSOR CUR_INCOME IS
        SELECT NVL(R.RESTAURANT_STATE, 'UNKNOWN') AS RESTAURANT_STATE, 
               NVL(C.CUISINE_NAME, 'UNKNOWN') AS CUISINE_NAME, 
               NVL(SUM(O.AMOUNT_PAID), 0) AS TOTAL
        FROM RESTAURANTS R
        FULL OUTER JOIN CUISINE C ON R.CUISINE_ID = C.CUISINE_ID
        FULL OUTER JOIN ORDERS O ON R.RESTAURANT_ID = O.RESTAURANT_ID
        GROUP BY R.RESTAURANT_STATE, C.CUISINE_NAME;

BEGIN
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('|        INCOME REPORT BY STATE                         |');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
    FOR INCOME_INFORMATION IN CUR_INCOME LOOP
        DBMS_OUTPUT.PUT_LINE('| STATE: ' || RPAD(INCOME_INFORMATION.RESTAURANT_STATE, 10) || 
                             ' | CUISINE: ' || RPAD(INCOME_INFORMATION.CUISINE_NAME, 15) || 
                             ' | TOTAL: $' || TO_CHAR(INCOME_INFORMATION.TOTAL, '99999.99') || ' |');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED WHILE GENERATING INCOME REPORT BY STATE.');
END;


/


CREATE OR REPLACE PROCEDURE UPDATE_MENU_ITEM_INVENTORY(
    P_RESTAURANT_NAME IN VARCHAR2,
    P_MENU_ITEM_NAME IN VARCHAR2,
    P_QUANTITY IN NUMBER,
    P_ACTION IN VARCHAR2 -- 'REDUCE' or 'INCREASE'
)
IS
    P_RESTAURANT_ID NUMBER;
    P_MENU_ITEM_ID NUMBER;
    CHECK_QUANTITY NUMBER;
BEGIN
    -- Find the restaurant ID using the provided restaurant name
    P_RESTAURANT_ID := FIND_RESTAURANT_ID(P_RESTAURANT_NAME);
    
    -- Find the menu item ID using the provided menu item name
    P_MENU_ITEM_ID := FIND_MENU_ITEM_ID(P_MENU_ITEM_NAME);

    -- Retrieve the current quantity from the database
    SELECT QUANTITY INTO CHECK_QUANTITY FROM RESTAURANT_INVENTORY WHERE RESTAURANT_ID = P_RESTAURANT_ID AND MENU_ITEM_ID = P_MENU_ITEM_ID;

    IF P_ACTION = 'REDUCE' THEN
        IF CHECK_QUANTITY - P_QUANTITY >= 0 THEN
            -- UPDATE THE QUANTITY TO REDUCE THE MENU ITEM IN THE INVENTORY
            UPDATE RESTAURANT_INVENTORY
            SET QUANTITY = QUANTITY - P_QUANTITY
            WHERE RESTAURANT_ID = P_RESTAURANT_ID
            AND MENU_ITEM_ID = P_MENU_ITEM_ID;
            
            -- OUTPUT A MESSAGE INDICATING THAT THE MENU ITEM INVENTORY HAS BEEN UPDATED
            DBMS_OUTPUT.PUT_LINE('Menu item inventory reduced for Restaurant ' || P_RESTAURANT_NAME || ' and Menu Item ' || P_MENU_ITEM_NAME);
        ELSE 
            DBMS_OUTPUT.PUT_LINE('There is not enough menu items to reduce the inventory.');
        END IF;
    ELSIF P_ACTION = 'INCREASE' THEN
        -- UPDATE THE QUANTITY TO INCREASE THE MENU ITEM IN THE INVENTORY
        UPDATE RESTAURANT_INVENTORY
        SET QUANTITY = QUANTITY + P_QUANTITY
        WHERE RESTAURANT_ID = P_RESTAURANT_ID
        AND MENU_ITEM_ID = P_MENU_ITEM_ID;
        
        -- OUTPUT A MESSAGE INDICATING THAT THE MENU ITEM INVENTORY HAS BEEN UPDATED
        DBMS_OUTPUT.PUT_LINE('Menu item inventory increased for Restaurant ' || P_RESTAURANT_NAME || ' and Menu Item ' || P_MENU_ITEM_NAME);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Invalid action. Please specify either "REDUCE" or "INCREASE".');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        -- Handle case when no data is found for the provided names
        DBMS_OUTPUT.PUT_LINE('Restaurant or Menu Item not found.');
    WHEN OTHERS THEN
        -- OUTPUT AN ERROR MESSAGE IF AN EXCEPTION OCCURS DURING THE UPDATE
        DBMS_OUTPUT.PUT_LINE('Error updating menu item inventory: ' || SQLERRM);
END;
/


CREATE OR REPLACE PROCEDURE GENERATE_REPORT_MENU_ITEMS IS
  CURSOR C1 IS
 SELECT NVL(M.NAME, 'N/A') AS MENU_ITEM_NAME, NVL(C.CUISINE_NAME, 'N/A') AS CUISINE_NAME, SUM(NVL(RI.QUANTITY, 0)) AS QUANTITY
 FROM MENU_ITEMS M
 FULL OUTER JOIN CUISINE C ON C.CUISINE_ID = M.CUISINE_ID
 FULL OUTER JOIN RESTAURANT_INVENTORY RI ON M.MENU_ITEM_ID = RI.MENU_ITEM_ID
 GROUP BY M.NAME, C.CUISINE_NAME;

BEGIN
  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('|               MENU ITEMS REPORT                      |');
  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
  DBMS_OUTPUT.PUT_LINE('|      MENU ITEM       |      CUISINE      |  QUANTITY  |');
  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');

  FOR ITEM IN C1 LOOP
    DBMS_OUTPUT.PUT_LINE('| ' || RPAD(ITEM.MENU_ITEM_NAME, 20) || ' | ' || RPAD(ITEM.CUISINE_NAME, 18) || ' | ' || TO_CHAR(ITEM.QUANTITY, '99999') || ' |');
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
END;


/

CREATE OR REPLACE PROCEDURE RECOMMEND_TO_CUSTOMER (
P_CUSTOMER_NAME IN VARCHAR2,
P_CUISINE_NAME IN VARCHAR2
)
AS
V_RESTAURANT_ID NUMBER;
V_RESTAURANT_NAME VARCHAR2(50);
V_AVG_STARS NUMBER;
V_ORDER_COUNT NUMBER;
V_CUISINE_TYPE_ID NUMBER;
V_CUSTOMER_ID NUMBER;
BEGIN
-- FIND THE BEST RATED RESTAURANT FOR THE GIVEN CUISINE TYPE
V_CUISINE_TYPE_ID := FIND_CUISINE_TYPE_ID(P_CUISINE_NAME);
IF V_CUISINE_TYPE_ID < 0 THEN
DBMS_OUTPUT.PUT_LINE('ERROR: CUISINE NOT FOUND.');
RETURN;
END IF;
V_CUSTOMER_ID := FIND_CUSTOMER_ID(P_CUSTOMER_NAME);
IF V_CUSTOMER_ID < 0 THEN
DBMS_OUTPUT.PUT_LINE('ERROR: CUSTOMER NOT FOUND.');
RETURN;
END IF;
SELECT R.RESTAURANT_ID, R.RESTAURANT_NAME, AVG(RV.STARS_GIVEN)
INTO V_RESTAURANT_ID, V_RESTAURANT_NAME, V_AVG_STARS
FROM RESTAURANTS R
JOIN REVIEWS RV ON R.RESTAURANT_ID = RV.RESTAURANT_ID
WHERE R.CUISINE_ID = V_CUISINE_TYPE_ID
GROUP BY R.RESTAURANT_ID, R.RESTAURANT_NAME
ORDER BY AVG(RV.STARS_GIVEN) DESC;

DBMS_OUTPUT.PUT_LINE('Best rated RESTAURANT for ' ||

P_CUISINE_NAME || ' is : ' || V_RESTAURANT_NAME);

-- CHECK IF THE CUSTOMER HAS VISITED THE BEST RATED RESTAURANT SERVING THIS CUISINE TYPE IN THE PAST
SELECT COUNT(*)
INTO V_ORDER_COUNT
FROM ORDERS O
JOIN MENU_ITEMS M ON O.MENU_ITEM_ID = M.MENU_ITEM_ID
WHERE O.CUSTOMER_ID = V_CUSTOMER_ID
AND O.RESTAURANT_ID = V_RESTAURANT_ID
AND M.CUISINE_ID = V_CUISINE_TYPE_ID;

IF V_ORDER_COUNT = 0 THEN
-- INSERT RECOMMENDATION IF THE CUSTOMER HAS NOT VISITED THE BEST RATED RESTAURANT SERVING THIS CUISINE TYPE BEFORE
INSERT INTO RECOMMENDATIONS (RECOMMENDATION_ID, CUSTOMER_ID, RECOMMENDED_RESTAURANT_ID, RECOMMENDATION_DATE)
VALUES (RECOMMENDATION_ID_SEQUENCE.NEXTVAL, V_CUSTOMER_ID, V_RESTAURANT_ID, SYSDATE);
DBMS_OUTPUT.PUT_LINE('INSERTING RECOMMENDATION AS THE CUSTOMER HAS NOT VISITED THE BEST RATED RESTAURANT SERVING ' || P_CUISINE_NAME
|| ' CUISINE TYPE BEFORE');
COMMIT;
ELSE
DBMS_OUTPUT.PUT_LINE('CUSTOMER HAS ALREADY VISITED THE BEST RATED RESTAURANT SERVING THIS CUISINE TYPE: ' || P_CUISINE_NAME);
END IF;
DBMS_OUTPUT.PUT_LINE('RECOMMEND_TO_CUSTOMER EXECUTED SUCCESSFULLY');
EXCEPTION
WHEN NO_DATA_FOUND THEN
DBMS_OUTPUT.PUT_LINE('NO RECOMMENDATIONS FOUND FOR THE GIVEN CRITERIA.');
WHEN OTHERS THEN
DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED: ' || SQLERRM);
END;

/
create or replace PROCEDURE LIST_ORDERS_AT_REST_ON_DATE(
    REST_NAME IN VARCHAR2,
    ORD_DATE IN DATE
)
IS
    CURSOR ORDERS_CURSOR IS
        SELECT ORDER_ID, CUSTOMER_ID, MENU_ITEM_ID, AMOUNT_PAID, TIP
        FROM ORDERS O
        JOIN RESTAURANTS R ON O.RESTAURANT_ID = R.RESTAURANT_ID
        WHERE R.RESTAURANT_NAME = REST_NAME
        AND TRUNC(O.ORDER_DATE) = TRUNC(ORD_DATE);

    ORDER_REC ORDERS_CURSOR%ROWTYPE;
BEGIN
    -- OPEN THE CURSOR
    OPEN ORDERS_CURSOR;

    -- FETCH ORDERS AND PRINT DETAILS
    DBMS_OUTPUT.PUT_LINE('ORDERS AT ' || REST_NAME || ' ON ' || TO_CHAR(ORD_DATE, 'YYYY-MM-DD') || ':');
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    LOOP
        FETCH ORDERS_CURSOR INTO ORDER_REC;
        EXIT WHEN ORDERS_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('ORDER ID: ' || ORDER_REC.ORDER_ID);
        DBMS_OUTPUT.PUT_LINE('CUSTOMER ID: ' || ORDER_REC.CUSTOMER_ID);
        DBMS_OUTPUT.PUT_LINE('MENU ITEM ID: ' || ORDER_REC.MENU_ITEM_ID);
        DBMS_OUTPUT.PUT_LINE('AMOUNT PAID: $' || ORDER_REC.AMOUNT_PAID);
        DBMS_OUTPUT.PUT_LINE('TIP: $' || ORDER_REC.TIP);
        DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    END LOOP;

    -- CLOSE THE CURSOR
    CLOSE ORDERS_CURSOR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO ORDERS FOUND AT ' || REST_NAME || ' ON ' || TO_CHAR(ORD_DATE, 'YYYY-MM-DD'));
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('AN ERROR OCCURRED: ' || SQLERRM);
END;

/
CREATE OR REPLACE PROCEDURE top_rest_by_state
IS
    CURSOR state_cur IS
        SELECT DISTINCT r.restaurant_state
        FROM Restaurants r;

    TYPE state_rec_type IS RECORD (
        restaurant_state Restaurants.restaurant_state%TYPE
    );

    state_rec state_rec_type;

    CURSOR restaurant_cur (p_state Restaurants.restaurant_state%TYPE) IS
        SELECT r.restaurant_name, SUM(o.amount_paid) AS total_amount_paid
        FROM Restaurants r
        JOIN Orders o ON r.restaurant_id = o.restaurant_id
        WHERE r.restaurant_state = p_state
        GROUP BY r.restaurant_name
        ORDER BY total_amount_paid DESC; -- Ordering within each group

    restaurant_rec restaurant_cur%ROWTYPE;

BEGIN
    OPEN state_cur;
    LOOP
        FETCH state_cur INTO state_rec;
        EXIT WHEN state_cur%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('Top 3 restaurants for state: ' || state_rec.restaurant_state);

        OPEN restaurant_cur(state_rec.restaurant_state);
        FOR i IN 1..3 LOOP -- Fetch top 3 restaurants
            FETCH restaurant_cur INTO restaurant_rec;
            EXIT WHEN restaurant_cur%NOTFOUND;

            DBMS_OUTPUT.PUT_LINE('Restaurant: ' || restaurant_rec.restaurant_name ||
                                 ', Total Amount Paid: ' || restaurant_rec.total_amount_paid);
        END LOOP;
        CLOSE restaurant_cur;

        DBMS_OUTPUT.PUT_LINE('------------------');
    END LOOP;
    CLOSE state_cur;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('The data is not Found ' || SQLERRM);
END;
/




CREATE OR REPLACE PROCEDURE LIST_RECOMMENDATIONS
AS
    CURSOR RECOMMENDATION_CURSOR IS
        SELECT C.NAME AS CUSTOMER_NAME, R.RESTAURANT_NAME, M.CUISINE_NAME, AVG(RV.STARS_GIVEN) AS AVG_STARS
        FROM RECOMMENDATIONS REC
        JOIN CUSTOMERS C ON REC.CUSTOMER_ID = C.CUSTOMER_ID
        JOIN RESTAURANTS R ON REC.RECOMMENDED_RESTAURANT_ID = R.RESTAURANT_ID
        JOIN CUISINE M ON R.CUISINE_ID = M.CUISINE_ID
        LEFT JOIN REVIEWS RV ON REC.RECOMMENDED_RESTAURANT_ID = RV.RESTAURANT_ID
        GROUP BY C.NAME, R.RESTAURANT_NAME, M.CUISINE_NAME;

    V_CUSTOMER_NAME CUSTOMERS.NAME%TYPE;
    V_RESTAURANT_NAME RESTAURANTS.RESTAURANT_NAME%TYPE;
    V_CUISINE_NAME CUISINE.CUISINE_NAME%TYPE;
    V_AVG_STARS NUMBER;
BEGIN
    OPEN RECOMMENDATION_CURSOR;
    LOOP
        FETCH RECOMMENDATION_CURSOR INTO V_CUSTOMER_NAME, V_RESTAURANT_NAME, V_CUISINE_NAME, V_AVG_STARS;
        EXIT WHEN RECOMMENDATION_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE('CUSTOMER: ' || V_CUSTOMER_NAME || ', RECOMMENDED RESTAURANT: ' || V_RESTAURANT_NAME || ', CUISINE: ' || V_CUISINE_NAME || ', AVERAGE STARS: ' || NVL(TO_CHAR(V_AVG_STARS), 'NOT REVIEWED YET'));
    END LOOP;
    CLOSE RECOMMENDATION_CURSOR;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED: ' || SQLERRM);
END;

/

CREATE OR REPLACE TRIGGER UPDATE_INVENTORY_AFTER_ORDER
AFTER INSERT ON ORDERS
FOR EACH ROW
BEGIN
    -- REDUCE THE INVENTORY BY 1 WHENEVER AN ORDER IS PLACED
    UPDATE RESTAURANT_INVENTORY
    SET QUANTITY = QUANTITY - 1
    WHERE RESTAURANT_ID = :NEW.RESTAURANT_ID AND MENU_ITEM_ID = :NEW.MENU_ITEM_ID; -- CHANGED 'MENU_ITEMS_ID' TO 'MENU_ITEM_ID'
    
    IF SQL%ROWCOUNT = 0 THEN
        -- IF NO ROWS ARE UPDATED, IT COULD MEAN INVENTORY IS NOT TRACKED
        DBMS_OUTPUT.PUT_LINE('INVENTORY UPDATE FAILED: NO INVENTORY RECORD.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('INVENTORY UPDATED SUCCESSFULLY.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR OCCURRED IN UPDATING INVENTORY: ' || SQLERRM);
END UPDATE_INVENTORY_AFTER_ORDER;
/
BEGIN
-- ADD DATA TO CUISINE TABLE 
ADD_CUISINE('AMERICAN');
ADD_CUISINE('ITALIAN');
ADD_CUISINE('BBQ');
ADD_CUISINE('INDIAN');
ADD_CUISINE('ETHIOPIAN');

 --ADD DATA TO RESTAURANT TABLE
 
ADD_NEW_RESTAURANT('RIBS_R_US','MAIN ST','CATONSVILLE ','CA','21250','AMERICAN');
ADD_NEW_RESTAURANT('BELLA ITALIA','OAK ST','ELLICOT CITY','MD','21043','ITALIAN');
ADD_NEW_RESTAURANT('SELASIE','MOUNTAIN ST','COLUMBIA ','PA','16822','ETHIOPIAN');
ADD_NEW_RESTAURANT('ROMA','BEACHFIELD ST','HENDERSON ','MD','21043','ITALIAN');
ADD_NEW_RESTAURANT('TAJ MAHAL','MAIDEN ST','BROOKLYN ','NY','10013','INDIAN');
ADD_NEW_RESTAURANT('BULL ROAST','CHOICE ST','QUEENS','NY','10013','BBQ');
ADD_NEW_RESTAURANT('ETHIOP','PANNIER ST','PITTSBURGH ','PA','16822','ETHIOPIAN');

END;
/
BEGIN
DBMS_OUTPUT.PUT_LINE('=====================================================================');
DBMS_OUTPUT.PUT_LINE('==================BELOW ARE MEMBER 1 OPERATIONS======================');
DBMS_OUTPUT.PUT_LINE('=====================================================================');
END;
/
DECLARE
CUISINE_NAME_VALUE VARCHAR2(100) := 'AMERICAN';
CUISINE_NAME_VALUES VARCHAR2(100) := 'ETHIOPIAN';
CUISINE_NAME_IAT VARCHAR2(100) := 'ITALIAN';
BEGIN
DBMS_OUTPUT.PUT_LINE('=====Display restaurant by cuisine: Input is ‘AMERICAN=======');
DBMS_OUTPUT.PUT_LINE('');
-- CALL DISPLAY_RESTAURANTS_BY_CUISINE PROCEDURE
DBMS_OUTPUT.PUT_LINE('RESTAURANTS OFFERING ' || CUISINE_NAME_VALUE || ':');
DISPLAY_RESTAURANTS_BY_CUISINE(CUISINE_NAME_VALUE);
DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('=====Display restaurant by cuisine: Input is ‘Ethiopian=======');
DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('RESTAURANTS OFFERING ' || CUISINE_NAME_VALUES || ':');
DISPLAY_RESTAURANTS_BY_CUISINE(CUISINE_NAME_VALUES);
DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('=====Display restaurant by cuisine: Input is ‘Italian=======');
DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('RESTAURANTS OFFERING ' || CUISINE_NAME_IAT || ':');
DISPLAY_RESTAURANTS_BY_CUISINE(CUISINE_NAME_IAT);
END;
/
BEGIN


-- ADD DATA IN WAITER TABLE
    
 ADD_WAITER('JACK', 'RIBS_R_US');
 ADD_WAITER('JILL', 'RIBS_R_US');
 ADD_WAITER('WENDY', 'RIBS_R_US');
 ADD_WAITER('HAILEY', 'RIBS_R_US');
 ADD_WAITER('MARY', 'BELLA ITALIA');
 ADD_WAITER('PAT', 'BELLA ITALIA');
 ADD_WAITER('MICHAEL', 'BELLA ITALIA');
 ADD_WAITER('RAKESH', 'BELLA ITALIA');
 ADD_WAITER('VERMA', 'BELLA ITALIA');
 ADD_WAITER('MIKE', 'ROMA');
 ADD_WAITER('JUDY', 'ROMA');
 ADD_WAITER('TREVOR', 'SELASIE');
 ADD_WAITER('TRISHA', 'ETHIOP');
 ADD_WAITER('HANNAH', 'BULL ROAST');
 ADD_WAITER('GUPTA', 'TAJ MAHAL');
 
 END;
 /
 BEGIN
DBMS_OUTPUT.PUT_LINE('=================================');
DBMS_OUTPUT.PUT_LINE('=====MEMBER 2 OPERATIONS ========');
DBMS_OUTPUT.PUT_LINE('=================================');
END;
/
--SHOW THE WAITERS WHO WORK AT BELLA ITALIA
DECLARE
WAITERS VARCHAR(30); --VARIABLE TO STORE THE WAITER'S NAMES
BEGIN
DBMS_OUTPUT.PUT_LINE('LISTOF WAITERS IN BELLA ITALIA RESTAURANT ARE ');
SHOW_WAITERS('BELLA ITALIA', WAITERS); -- CALL THE PROCEDURE
DBMS_OUTPUT.PUT_LINE(' ');

DBMS_OUTPUT.PUT_LINE('LISTOF WAITERS IN TAJ MAHAL RESTAURANT ARE ');

SHOW_WAITERS('TAJ MAHAL', WAITERS); -- CALL THE PROCEDURE

END;
/
 BEGIN

--ADD DATA IN MENU ITEM TABLE

--ADD MENU ITEMS FOR AMERICAN CUISINE
 ADD_MENU_ITEM('BURGER', 10, 'AMERICAN');
 ADD_MENU_ITEM('FRIES', 5, 'AMERICAN');
 ADD_MENU_ITEM('PASTA', 15, 'AMERICAN');
 ADD_MENU_ITEM('SALAD', 10, 'AMERICAN');
 ADD_MENU_ITEM('SALMON', 20, 'AMERICAN');
 -- ADD MENU ITEMS FOR ITALIAN CUISINE
 ADD_MENU_ITEM('LASAGNA', 15, 'ITALIAN');
 ADD_MENU_ITEM('MEATBALLS', 10, 'ITALIAN');
 ADD_MENU_ITEM('SPAGHETTI', 15, 'ITALIAN');
 ADD_MENU_ITEM('PIZZA', 20, 'ITALIAN');

 -- ADD MENU ITEMS FOR ETHIOPIAN CUISINE
 ADD_MENU_ITEM('MEAT CHUNKS', 12, 'ETHIOPIAN');
 ADD_MENU_ITEM('LEGUME STEW', 10, 'ETHIOPIAN');
 ADD_MENU_ITEM('FLATBREAD', 3, 'ETHIOPIAN');

 -- ADD MENU ITEMS FOR BBQ CUISINE
 ADD_MENU_ITEM('STEAK', 25, 'BBQ');
 ADD_MENU_ITEM('PORK LOIN', 15, 'BBQ');
 ADD_MENU_ITEM('FILET MIGNON', 30, 'BBQ');
 
 -- ADD MENU ITEMS FOR INDIAN CUISINE
ADD_MENU_ITEM('DAL SOUP', 10, 'INDIAN');
ADD_MENU_ITEM('RICE', 5, 'INDIAN');
ADD_MENU_ITEM('TANDOORI CHICKEN', 10, 'INDIAN');
ADD_MENU_ITEM('SAMOSA', 8, 'INDIAN');

 --ADD MENU ITEM DATA TO INVENTORY TABLE
 ADD_ITEMS_INVENTORY('BURGER', 'RIBS_R_US', 50);
 ADD_ITEMS_INVENTORY('FRIES', 'RIBS_R_US', 150);
 ADD_ITEMS_INVENTORY('LASAGNA', 'BELLA ITALIA', 10);
 ADD_ITEMS_INVENTORY('MEATBALLS', 'BELLA ITALIA', 5);
 ADD_ITEMS_INVENTORY('MEAT CHUNKS', 'SELASIE', 150);
 ADD_ITEMS_INVENTORY('LEGUME STEW', 'SELASIE', 150);
 ADD_ITEMS_INVENTORY('FLATBREAD', 'SELASIE', 500);
 ADD_ITEMS_INVENTORY('PIZZA', 'BELLA ITALIA', 100);
 ADD_ITEMS_INVENTORY('SPAGHETTI', 'BELLA ITALIA', 100);
 

ADD_ITEMS_INVENTORY('STEAK', 'BULL ROAST', 15);
ADD_ITEMS_INVENTORY('PORK LOIN', 'BULL ROAST', 50);
ADD_ITEMS_INVENTORY('FILET MIGNON', 'BULL ROAST', 5);
ADD_ITEMS_INVENTORY('DAL SOUP', 'TAJ MAHAL', 50);
ADD_ITEMS_INVENTORY('RICE', 'TAJ MAHAL', 500);
ADD_ITEMS_INVENTORY('SAMOSA', 'TAJ MAHAL', 150);

ADD_ITEMS_INVENTORY('MEAT CHUNKS', 'ETHIOP', 150);
ADD_ITEMS_INVENTORY('LEGUME STEW', 'ETHIOP', 150);
ADD_ITEMS_INVENTORY('FLATBREAD', 'ETHIOP', 500);

END;
/
BEGIN
DBMS_OUTPUT.PUT_LINE('=================================');
DBMS_OUTPUT.PUT_LINE('=====MEMBER 3 OPERATIONS ========');
DBMS_OUTPUT.PUT_LINE('=================================');
END;
/
BEGIN 
    DBMS_OUTPUT.PUT_LINE('---------- Initial Inventory Report for All Restaurants ----------');
    GENERATE_REPORT_MENU_ITEMS;
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('--------------- Initial Inventory for Ethiop restaurant -------------------');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');

END;
/
SELECT RPAD(r.restaurant_name, 20, ' ') AS restaurant_name,
       RPAD(ri.menu_item_name, 30, ' ') AS menu_item_name,
       TO_CHAR(ri.quantity, '999999999') AS quantity
from restaurant_inventory ri, restaurants r 
where ri.restaurant_id = r.restaurant_id and r.restaurant_name = 'ETHIOP';
/
BEGIN
    UPDATE_MENU_ITEM_INVENTORY('TAJ MAHAL', 'RICE', 25, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('SELASIE', 'MEAT CHUNKS', 50, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('BULL ROAST', 'FILET MIGNON', 2, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('BULL ROAST', 'FILET MIGNON', 2, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('ETHIOP', 'MEAT CHUNKS', 30, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('ETHIOP', 'MEAT CHUNKS', 30, 'REDUCE');
    UPDATE_MENU_ITEM_INVENTORY('ETHIOP', 'LEGUME STEW', 20, 'REDUCE');
    DBMS_OUTPUT.PUT_LINE('--------------- Final Inventory for Ethiop restaurant -------------------');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');

END;
/
SELECT RPAD(r.restaurant_name, 20, ' ') AS restaurant_name,
       RPAD(ri.menu_item_name, 30, ' ') AS menu_item_name,
       TO_CHAR(ri.quantity, '999999999') AS quantity
from restaurant_inventory ri, restaurants r 
where ri.restaurant_id = r.restaurant_id and r.restaurant_name = 'ETHIOP';
/
BEGIN 
    DBMS_OUTPUT.PUT_LINE('---------- Initial Inventory Report for All Restaurants ----------');
    GENERATE_REPORT_MENU_ITEMS;
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------------');
END;
/
BEGIN


   --ADD CUSTOMER DATA TO CUSTOMERS TABLE
ADD_CUSTOMERS('CUST1', 'CUSTOMER1@GMAIL.COM', '45342 JAMESDAVE', 'BALTIMORE', 'MD', '21045', '1432432');
ADD_CUSTOMERS('CUST11', 'CUSTOMER2@GMAIL.COM', '3242 OKSDAVE', 'BALTIMORE', 'MD', '21045', '1432332');
ADD_CUSTOMERS('CUST3', 'CUSTOMER3@GMAIL.COM', '3242 OKSDAVE', 'BALTIMORE', 'MD', '21046', '1432332');
ADD_CUSTOMERS('CUST111', 'CUSTOMER111@GMAIL.COM', '34342 THANLYOUDAVE', 'BALTIMORE', 'MD', '21045', '143221432');
ADD_CUSTOMERS('CUSTNY1', 'CUSTOMERNY1@GMAIL.COM', '454222 ITSOKSDAVE', 'NY', 'MD', '10045', '1432432');
ADD_CUSTOMERS('CUSTNY2', 'CUSTOMERNY2@GMAIL.COM', '454222 ITSOKSDAVE', 'NY', 'MD', '10045', '1432432');
ADD_CUSTOMERS('CUSTNY3', 'CUSTOMERNY3@GMAIL.COM', '454222 ITSOKSDAVE', 'NY', 'MD', '10045', '1432432');
ADD_CUSTOMERS('CUSTPA1', 'CUSTOMERPA1@GMAIL.COM', '454222 ITSOKSDAVE', 'PHILI', 'MD', '16822', '1432432');
ADD_CUSTOMERS('CUSTPA2', 'CUSTOMERPA2@GMAIL.COM', '454222 ITSOKSDAVE', 'PHILI', 'MD', '16822', '1432432');
ADD_CUSTOMERS('CUSTPA3', 'CUSTOMERPA3@GMAIL.COM', '454222 ITSOKSDAVE', 'PHILI', 'MD', '16822', '1432432');
ADD_CUSTOMERS('CUSTPA4', 'CUSTOMERPA4@GMAIL.COM', '545 ITSROADWAY', 'PHILI', 'MD', '16822', '2433222');
ADD_CUSTOMERS('CUSTPA5', 'CUSTOMERPA5@GMAIL.COM', '1234 LIBERTY AVE', 'PHILI', 'MD', '16822', '2556654');
ADD_CUSTOMERS('CUSTPA6', 'CUSTOMERPA6@GMAIL.COM', '6789 FREEDOM LN', 'PHILI', 'MD', '16822', '3667788');
 -- ADD DATA TO ORDER TABLE
    
ADD_ORDER('BELLA ITALIA', 'CUST1', 'PIZZA', 'MARY', TO_DATE('2024-03-10', 'YYYY-MM-DD'), 10);
ADD_ORDER('BELLA ITALIA', 'CUST1', 'PIZZA', 'MARY', TO_DATE('2024-03-10', 'YYYY-MM-DD'), 10);
ADD_ORDER('BELLA ITALIA', 'CUST11', 'SPAGHETTI', 'MARY', TO_DATE('2024-03-15', 'YYYY-MM-DD'), 15); 
ADD_ORDER('BELLA ITALIA', 'CUST11', 'SPAGHETTI', 'MARY', TO_DATE('2024-03-15', 'YYYY-MM-DD'), 15);
ADD_ORDER('BELLA ITALIA', 'CUST11', 'PIZZA', 'MARY', TO_DATE('2024-03-15', 'YYYY-MM-DD'), 10);
ADD_ORDER('BELLA ITALIA', 'CUST11', 'PIZZA', 'MARY', TO_DATE('2024-03-15', 'YYYY-MM-DD'), 10);
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 30);
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 30); 
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 30);
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 30);
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 30);
ADD_ORDER('BULL ROAST', 'CUSTNY1', 'FILET MIGNON', 'HANNAH', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 30);
ADD_ORDER('BULL ROAST', 'CUSTNY2', 'PORK LOIN', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 15);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12); 
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JACK', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JACK', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JACK', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JACK', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JILL', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JILL', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JILL', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 10);
ADD_ORDER('RIBS_R_US', 'CUSTNY1', 'BURGER', 'JILL', TO_DATE('2024-04-02', 'YYYY-MM-DD'), 10);
ADD_ORDER('BULL ROAST', 'CUSTNY2', 'PORK LOIN', 'HANNAH', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 15);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTNY2', 'MEAT CHUNKS', 'TREVOR', TO_DATE('2024-04-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('ETHIOP', 'CUSTPA1', 'MEAT CHUNKS', 'TRISHA', TO_DATE('2024-05-10', 'YYYY-MM-DD'), 12);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10); 
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 10);  
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('SELASIE', 'CUSTPA2', 'LEGUME STEW', 'TREVOR', TO_DATE('2024-05-11', 'YYYY-MM-DD'), 10);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);
ADD_ORDER('TAJ MAHAL', 'CUSTPA2', 'SAMOSA', 'GUPTA', TO_DATE('2024-05-01', 'YYYY-MM-DD'), 8);

END;
/
BEGIN
DBMS_OUTPUT.PUT_LINE('=================================');
DBMS_OUTPUT.PUT_LINE('=====MEMBER 4 OPERATIONS ========');
DBMS_OUTPUT.PUT_LINE('=================================');
END;
/
BEGIN
LIST_ORDERS_AT_REST_ON_DATE('RIBS_R_US' , TO_DATE('2024-04-01', 'YYYY-MM-DD'));
LIST_ORDERS_AT_REST_ON_DATE('SELASIE' , TO_DATE('2024-04-01', 'YYYY-MM-DD'));

END;
/
BEGIN
    top_rest_by_state;
END;
/
BEGIN

-- ADD DATA TO REVIEW TABLE 
ADD_REVIEW('CUST1@GMAIL.COM', 'RIBS_R_US', 4, 'WONDERFUL PLACE, BUT EXPENSIVE');
ADD_REVIEW('CUST1@GMAIL.COM', 'BELLA ITALIA', 2, 'VERY BAD FOOD. I’M ITALIAN AND BELLA ITALIA DOES NOT GIVE YOU AUTHENTIC ITALIAN FOOD');
ADD_REVIEW('ABC@ABC.COM', 'RIBS_R_US', 4, 'I LIKED THE FOOD. GOOD EXPERIENCE');
ADD_REVIEW('DCE@ABC.COM', 'RIBS_R_US', 5, 'EXCELLENT');
ADD_REVIEW('ABC@ABC.COM', 'BELLA ITALIA', 3, 'SO-SO');
ADD_REVIEW('ABC@ABC.COM', 'SELASIE', 4, 'I LIKED THE FOOD. AUTHENTIC ETHIOPIAN EXPERIENCE');
ADD_REVIEW('CUST1@GMAIL.COM', 'SELASIE', 5, 'EXCELLENT FLAVOR. HIGHLY RECOMMENDED');
ADD_REVIEW('ABC@ABC.COM', 'RIBS_R_US', 2, 'SO-SO. LOW QUALITY BEEF');
ADD_REVIEW('CUST1@GMAIL.COM', 'TAJ MAHAL', 4, 'I ENJOYED THEIR SAMOSAS, BUT DID NOT LIKE THE DAL');
ADD_REVIEW('ZZZ@ABC.COM', 'TAJ MAHAL', 5, 'EXCELLENT SAMOSAS');
ADD_REVIEW('SURAJIT@ABC.COM', 'TAJ MAHAL', 3, 'NOT REALLY AUTHENTIC');
ADD_REVIEW('DCE@ABC.COM', 'BULL ROAST', 5, 'EXCELLENT');
ADD_REVIEW('ABC@ABC.COM', 'BULL ROAST', 3, 'JUST FINE');
ADD_REVIEW('ABC@ABC.COM', 'BULL ROAST', 4, 'I LIKED THE FOOD');
ADD_REVIEW('CUST1@GMAIL.COM', 'SELASIE', 5, 'EXCELLENT FLAVOR.HIGHLY RECOMMENDED');

END;
/
BEGIN
DBMS_OUTPUT.PUT_LINE('=================================');
DBMS_OUTPUT.PUT_LINE('=====MEMBER 5 OPERATIONS ========');
DBMS_OUTPUT.PUT_LINE('=================================');
END;
/
DECLARE
V_CUSTOMER_NAME VARCHAR2(50) := 'CUST111'; -- REPLACE WITH VALID CUSTOMER ID
V_CUISINE_NAME VARCHAR2(50) := 'BBQ'; -- REPLACE WITH VALID CUISINE NAME
BEGIN
-- CALL BUY OR BEWARE PROCEDURE
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
BUY_OR_BEWARE(3);
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
-- CALL RECOMMEND_TO_CUSTOMER PROCEDURE
DBMS_OUTPUT.PUT_LINE('OPERATING RECOMMEND_TO_CUSTOMER OPERATION');
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
DBMS_OUTPUT.PUT_LINE('TEST CASE 1: ADD RECOMMENDATION.');
RECOMMEND_TO_CUSTOMER(V_CUSTOMER_NAME, V_CUISINE_NAME);
V_CUSTOMER_NAME := 'CUST111';
V_CUISINE_NAME := 'INDIAN';
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
RECOMMEND_TO_CUSTOMER(V_CUSTOMER_NAME, V_CUISINE_NAME);

DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
DBMS_OUTPUT.PUT_LINE('TEST CASE 2: INVALID DATA.');
V_CUSTOMER_NAME := 'XYZ';
V_CUISINE_NAME := 'INVALID';
RECOMMEND_TO_CUSTOMER(V_CUSTOMER_NAME, V_CUISINE_NAME);
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
-- TEST LIST_RECOMMENDATIONS PROCEDURE
DBMS_OUTPUT.PUT_LINE('LIST_RECOMMENDATIONS REPORT');
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
LIST_RECOMMENDATIONS;
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------------------');
END;
/
BEGIN
DBMS_OUTPUT.PUT_LINE('=====================================================================');
DBMS_OUTPUT.PUT_LINE('==================BELOW ARE MEMBER 1 OPERATIONS======================');
DBMS_OUTPUT.PUT_LINE('=====================================================================');
END;
/
DECLARE
CUISINE_NAME_VALUE VARCHAR2(100) := 'AMERICAN';
CUISINE_NAME_VALUES VARCHAR2(100) := 'ETHIOPIAN';
CUISINE_NAME_IAT VARCHAR2(100) := 'ITALIAN';
BEGIN

DBMS_OUTPUT.PUT_LINE('');
DBMS_OUTPUT.PUT_LINE('========REPORT INCOME BY STATE OF RESTAURANT========');
REPORT_INCOME;
END;
/

BEGIN
DBMS_OUTPUT.PUT_LINE('=================================');
DBMS_OUTPUT.PUT_LINE('=====MEMBER 2 OPERATIONS ========');
DBMS_OUTPUT.PUT_LINE('=================================');
END;
/
DECLARE
    TIPS NUMBER;
BEGIN 
    -- Show Jack's tips
    SHOW_TIPS_BY_WAITER('JACK', TIPS);
    
    -- Show Jill's tips
    SHOW_TIPS_BY_WAITER('JILL', TIPS);
    
    -- Show Wendy's tips
    SHOW_TIPS_BY_WAITER('WENDY', TIPS);
    
    -- Show Hailey's tips
    SHOW_TIPS_BY_WAITER('HAILEY', TIPS);
    
    -- Show Mary's tips
    SHOW_TIPS_BY_WAITER('MARY', TIPS);
    
    -- Show Pat's tips
    SHOW_TIPS_BY_WAITER('PAT', TIPS);
    
    -- Show Michael's tips
    SHOW_TIPS_BY_WAITER('MICHAEL', TIPS);
    
    -- Show Rakesh's tips
    SHOW_TIPS_BY_WAITER('RAKESH', TIPS);
    
    -- Show Verma's tips
    SHOW_TIPS_BY_WAITER('VERMA', TIPS);
    
    -- Show Mike's tips
    SHOW_TIPS_BY_WAITER('MIKE', TIPS);
    
    -- Show Judy's tips
    SHOW_TIPS_BY_WAITER('JUDY', TIPS);
    
    -- Show Trevor's tips
    SHOW_TIPS_BY_WAITER('TREVOR', TIPS);
    
    SHOW_TIPS_BY_WAITER('HANNAH', TIPS);

    SHOW_TIPS_BY_WAITER('TRISHA', TIPS);
    
    SHOW_TIPS_BY_WAITER('GUPTA', TIPS);


    
    SHOW_TIPS_BY_STATE('MD', TIPS);
    
    SHOW_TIPS_BY_STATE('CA', TIPS);
    
    SHOW_TIPS_BY_STATE('NY', TIPS);
    
    SHOW_TIPS_BY_STATE('PA', TIPS);

END;

/